app = ''
primary_region = 'ord'

[build]
  image = "ghcr.io/open-webui/open-webui:ollama"

[env]
  ENABLE_SIGNUP = "false"
  OLLAMA_BASE_URL = 'http://localhost:11434'
  OLLAMA_MODELS = '/app/backend/data/models'

[[mounts]]
  source = 'data'
  destination = '/app/backend/data'
  initial_size = '80gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-8x'
  memory = '16gb'
  gpu_kind = 'l40s'
